<?php
# This file was automatically generated by the MediaWiki 1.17.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings 

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

//require_once( "$IP/includes/DefaultSettings.php" );

//$wgReadOnly = "UPgrading....";

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "CleverTrail";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/trails";
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "info@clevertrail.com";
$wgPasswordSender   = "info@clevertrail.com";

$wgEnotifUserTalk      = true; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

//open external links in a new tab/window
$wgExternalLinkTarget = '_blank';

## Database settings
//change in global_constants.php
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "dbClevertrailWiki";
$wgDBuser           = "userCTWiki";
$wgDBpassword       = "coremonopoly24";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgFileExtensions = array('png','gif','jpg','jpeg');
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of ./languages/Language(.*).php
$wgLanguageCode = "en";

//Add the disambiguation namespaces
define("NS_DISAMBIGUATION", 100);
define("NS_DISAMBIGUATION_TALK", 101);
$wgExtraNamespaces[NS_DISAMBIGUATION] = "Disambiguation";
$wgExtraNamespaces[NS_DISAMBIGUATION_TALK] = "Disambiguation_talk";

#Set default searching
$wgNamespacesToBeSearchedDefault = array(
        NS_MAIN =>           true,
        NS_TALK =>           false,
        NS_USER =>           false,
        NS_USER_TALK =>      false,
        NS_PROJECT =>      false,
        NS_PROJECT_TALK => false,
        NS_IMAGE =>          false,
        NS_IMAGE_TALK =>     false,
        NS_MEDIAWIKI =>      false,
        NS_MEDIAWIKI_TALK => false,
        NS_TEMPLATE =>       false,
        NS_TEMPLATE_TALK =>  false,
        NS_HELP =>           false,
        NS_HELP_TALK =>      false,
        NS_CATEGORY =>       true,
        NS_CATEGORY_TALK =>  false,
		NS_DISAMBIGUATION => true,
		NS_DISAMBIGUATION_TALK => false
);

//localhost
$wgSecretKey = "3078460d76e9841c19ab727710f74fd43583d8517078bb7b93a97d18242818";
//clevertrail.com
//$wgSecretKey = "69e6cebaad7f6ddeb187522050466618902c43f2cb84f383de7e4279744197b1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "5f2f44d57bdb6847";

//disable write access to the api
$wgEnableWriteAPI = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "clevertrailskin";
//$wgDefaultSkin = "chick";
//$wgDefaultSkin = 'monobook';

## Remove some preferences that are inappropriate
$wgHiddenPrefs[] = 'skin';
$wgHiddenPrefs[] = 'language';
$wgHiddenPrefs[] = 'showtoc';
$wgHiddenPrefs[] = 'justify';
$wgHiddenPrefs[] = 'numberheadings';
$wgHiddenPrefs[] = 'rows';
$wgHiddenPrefs[] = 'cols';
$wgHiddenPrefs[] = 'previewonfirst';
$wgHiddenPrefs[] = 'previewontop';
$wgHiddenPrefs[] = 'externaleditor';
$wgHiddenPrefs[] = 'externaldiff';
$wgHiddenPrefs[] = 'uselivepreview';
$wgHiddenPrefs[] = 'showtoc';
$wgHiddenPrefs[] = 'justify';
$wgHiddenPrefs[] = 'numberheadings';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = "CleverTrail:Copyright";
$wgRightsUrl  = "http://creativecommons.org/licenses/by-nc/3.0/";
$wgRightsText = "Creative Commons Attribution-NonCommercial 3.0 Unported License";
$wgRightsIcon = "http://i.creativecommons.org/l/by-nc/3.0/88x31.png";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;


# End of automatically generated settings.
# Add more configuration options below.

$wgShowExceptionDetails = true;

//permissions
$wgGroupPermissions['*']['upload'] = true;
$wgGroupPermissions['*']['reupload'] = true;
$wgGroupPermissions['*']['reupload-own'] = true;
$wgGroupPermissions['*']['reupload-shared'] = true;
$wgGroupPermissions['user']['delete'] = true;
$wgGroupPermissions['user']['deletedhistory'] = true;
$wgGroupPermissions['user']['deletedtext'] = true;
$wgGroupPermissions['user']['undelete'] = true;


//ConfirmEdit (captcha)
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
require_once( "$IP/extensions/ConfirmEdit/ReCaptcha.php"); 
$wgCaptchaClass = 'ReCaptcha';
# http://localhost
$wgReCaptchaPublicKey = '6Lfcn8USAAAAAChVEM3bJ9C1O4DDyHADQzeGh1NA';
$wgReCaptchaPrivateKey = '6Lfcn8USAAAAABC8Vq3BMop_IOnrL4Wr3zAVxYgD';
# http://clevertrail.com
//$wgReCaptchaPublicKey = '6Lfbn8USAAAAABzYuVMIIVJjOs7GffYNVwjtRxnz';
//$wgReCaptchaPrivateKey = '6Lfbn8USAAAAAJ8ikhHN1AX1l3OAB8aDz3MQvCIY';

$wgGroupPermissions['*'             ]['skipcaptcha'] = false;
$wgGroupPermissions['user'          ]['skipcaptcha'] = true;
$wgGroupPermissions['autoconfirmed' ]['skipcaptcha'] = true;
$wgGroupPermissions['bot'           ]['skipcaptcha'] = true; // registered bots
$wgGroupPermissions['sysop'         ]['skipcaptcha'] = true;
$wgGroupPermissions['emailconfirmed']['skipcaptcha'] = true;
$ceAllowConfirmedEmail = true;

$wgCaptchaTriggers['edit']          = true; 
$wgCaptchaTriggers['create']        = true; 
$wgCaptchaTriggers['addurl']        = false; 
$wgCaptchaTriggers['createaccount'] = true;
$wgCaptchaTriggers['badlogin']      = true;


//MultipleUpload
require_once("$IP/extensions/MultiUpload/MultiUpload.php");
$wgUploadNavigationUrl = "$wgScriptPath/index.php?title=Special:MultipleUpload";
$wgMaxUploadFiles = 5;

//W4GRatingBar
require_once( $IP.'/extensions/W4GRatingBar/w4g_rb.php');
$wgW4GRB_Path='/extensions/W4GRatingBar';
$wgW4GRB_Settings['anonymous-voting-enabled'] = true;
$wgW4GRB_Settings['max-bars-per-page'] = 5;

# Maps
require_once( "$IP/extensions/Maps/Maps.php" );
$egMapsAvailableServices = array ('googlemaps3');
$egMapsDefaultService = 'googlemaps3';

//Discussion
require_once("$IP/extensions/Discussion/Discussion.php");

//CleverTrail Base Extension
require_once("$IP/extensions/CleverTrail/CleverTrailBaseExtension.php");

//CleverTrail Main Extension
require_once("$IP/extensions/CleverTrail/CleverTrailMainExtension.php");